# Generated by Django 5.2.8 on 2025-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreAuditLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('actor_service', models.TextField(blank=True, null=True)),
                ('action', models.TextField()),
                ('object_type', models.TextField(blank=True, null=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core.core_audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreSystemSetting',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core.core_system_setting',
                'managed': False,
            },
        ),
    ]
