# Generated by Django 5.2.8 on 2025-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsAudit',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.TextField()),
                ('success', models.BooleanField()),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts.accounts_audit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsAuthToken',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts.accounts_auth_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField()),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('locale', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts.accounts_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsRole',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('key', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts.accounts_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts.accounts_user',
                'managed': False,
            },
        ),
    ]
