# Generated by Django 5.2.8 on 2025-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestsMocktest',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField()),
                ('sections', models.JSONField()),
                ('is_published', models.BooleanField()),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mock_tests.mock_tests_mocktest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MockTestsOption',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'mock_tests_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MockTestsQuestion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('question_type', models.TextField()),
                ('prompt', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mock_tests.mock_tests_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MockTestsSubmission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('submission_payload', models.JSONField()),
                ('score', models.JSONField(blank=True, null=True)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mock_tests_submission',
                'managed': False,
            },
        ),
    ]
