# Generated by Django 5.2.8 on 2025-11-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestEngineTestsession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('test_id', models.UUIDField(blank=True, null=True)),
                ('session_type', models.TextField()),
                ('status', models.TextField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_section', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'test_engine.test_engine_testsession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestEngineSessionLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'test_engine.test_engine_session_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestEngineSessionSection',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('section_name', models.TextField()),
                ('status', models.TextField()),
                ('time_allowed_seconds', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'test_engine.test_engine_session_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestEngineSessionLock',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='test_engine.testenginetestsession')),
                ('locked_by', models.TextField()),
                ('locked_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_engine.test_engine_session_lock',
                'managed': False,
            },
        ),
    ]
